# Makefil for the include files

CPFLAGS += -I$(TOP)/include

DEPS += drivers/clk.h
DEPS += drivers/gpio.h
DEPS += drivers/uart.h
DEPS += drivers/matrix.h
DEPS += drivers/print.h

DEPS += mint/regmap.h
DEPS += mint/types.h
